<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="125879" started-at="2018-10-23T07:56:45Z" finished-at="2018-10-23T07:58:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="125879" started-at="2018-10-23T07:56:45Z" finished-at="2018-10-23T07:58:51Z">
      <class name="Testcases.MyAccountScripts">
        <test-method status="PASS" signature="beforeMethod(java.lang.String)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="beforeMethod" is-config="true" duration-ms="62946" started-at="2018-10-23T07:56:45Z" finished-at="2018-10-23T07:57:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="myAccountSummary()[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="myAccountSummary" duration-ms="62412" started-at="2018-10-23T07:57:48Z" finished-at="2018-10-23T07:58:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at Testcases.MyAccountScripts.myAccountSummary(MyAccountScripts.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myAccountSummary -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Testcases.MyAccountScripts@5db250b4]" name="afterMethod" is-config="true" duration-ms="432" started-at="2018-10-23T07:58:50Z" finished-at="2018-10-23T07:58:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myAccountSummary status=FAILURE method=MyAccountScripts.myAccountSummary()[pri:0, instance:Testcases.MyAccountScripts@5db250b4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- Testcases.MyAccountScripts -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
